import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="he" className="h-dvh w-dvw">
      <body className={(inter.className, "size-full")}>{children}</body>
    </html>
  );
}
